1144 store preferences
openmsupply/open-msupply pull request #1153
Opened 2023-02-08 21:32 UTC by roxy-dao

Closes #1144 
- Updated DB version
- Created table for store preferences
- Sync table

2023-02-08 21:34 UTC, roxy-dao commented on server/repository/src/migrations/v1_01_03/mod.rs
> +        sql!(connection, r#"DROP VIEW IF EXISTS item_is_visible;"#)?;
Moved this since it was done after 1-1-2 release

2023-02-12 20:39 UTC, mark-prins commented
an API for the preferences would be great!
Another time though.. it isn't critical to this piece of work: https://github.com/openmsupply/open-msupply/issues/1169

2023-02-12 22:16 UTC, mark-prins requested changes
👍 Looking good! One change requested please - the postgres migrations need a small fix.
Other than that, works very nicely

2023-02-12 23:13 UTC, mark-prins approved these changes
😁  and woo! preferences!!

2023-02-12 23:43 UTC, merged