#1210 Stocktake lines for stock lines with 0 snapshot quantity
openmsupply/open-msupply pull request #1219
Opened 2023-02-20 23:43 UTC by roxy-dao

Fixes #1210 

# 👩🏻‍💻 What does this PR do? 
Only load stock lines for stocktake and outbound shipments if stock lines have stock

# 🧪 How has/should this change been tested? 
- Have an item with multiple batches
- Have one or more of those batches with 0 available number of packs
- Try to create a stocktake or outbound shipment with said item

2023-02-21 03:01 UTC, andreievg commented
@roxy-dao, is_available deals with available quantity

2023-02-21 03:07 UTC, roxy-dao commented
> a31a987

2023-02-22 20:26 UTC, andreievg commented
> Shouldn't users not see the stock line if there's no available number of packs (since you shouldn't be able to allocate more than you have left)...? 🤔 Changed to total anyways

> Edit: If you create an outbound shipment with stock line a and assign nearly all the packs (keep as new), then create a new outbound shipment with same item, it creates a placeholder line for said item... so makes sense to me to use available number of packs instead of total number of packs.....

Sorry I should have explained.

For Outbound Shipments, in mSupply we still show those. `Total` = hasn't left facility, `Not Available` = in facility but it's been allocated to a shipments. If there is an urgent shipment we can still send `Not Available` (be reducing it form other shipment) and having that visible when issuing stock I think is the reason it's shown in mSupply

2023-02-22 22:28 UTC, mark-prins submitted a review, later dismissed
👍 changes look good thanks!
am wondering if it necessary to add a similar filter to the outbound shipment to catch the second part of the issue? There shouldn't be any 0 packs due to stocktakes now - and I'd hope that mSupply won't send us any stock lines with 0 quantity, so that's probably a theoretical problem rather than a real one

2023-02-22 22:31 UTC, mark-prins commented
Found a problem sorry - if you create a stocktake using master list or location then the test isn't applied and you can add stock lines which have zero quantity.

2023-02-22 22:31 UTC, mark-prins requested changes
Could you also add the filter to the stocktake creation by master list and location 🙏

2023-02-22 22:32 UTC, roxy-dao commented
> Could you also add the filter to the stocktake creation by master list and location 🙏

Yup, changing it right now to do frontend filter instead of be (: (need to update from develop first though 🤣 )

2023-02-23 00:41 UTC, roxy-dao commented on client/packages/common/src/types/schema.ts
> +  /**
Not sure why this was generated now... didn't go through with the associated PR?

2023-02-23 00:42 UTC, roxy-dao commented on client/packages/system/src/Stock/api/api.ts
> +      const filter = {
Andrei said to filter in FE... but Stocktake by Masterlist and Location are generated in BE so 🤷🏻

2023-02-23 22:14 UTC, andreievg approved these changes
thanks for changes. looks good, something that I would have done different but it's probably out of scope for the issue and not required for this to be merged:

> Andrei said to filter in FE... but Stocktake by Masterlist and Location are generated in BE so

They are but there is API for that, I would actually change API stocktake input to have an option:

```diff
input InsertStocktakeInput {
        description: String
        isLocked: Boolean
        stocktakeDate: NaiveDate
-       masterListId: String
-       locationId: String
+       addItems: StocktakeAddItems
+}
+
+input StocktakeAddItems {
+       from: StocktakeAddItemFrom!
+       id: String!
+       stocklineFilter: StockLineFilterInput
+}
+
+enum StocktakeAddItemFrom {
+       MASTER_LIST
+       LOCATION
 }
```

`stocklineFilter` would apply on top of masterlist/location filter. 

Also just noticed, that we usually get stock lines (outbound/stocktake edit line modal) from item.availableBatches, I think renaming to item.batches and  adding filter on the batch :

```diff
-    async fn available_batches(
+    async fn batches(
         &self,
         ctx: &Context<'_>,
         store_id: String,
+        filter: Option<StockLineFilter>,
```

(fyi, the loader would need to use payload on IdPair, similar to `ItemStatsForItemLoader`)

2023-02-27 01:08 UTC, mark-prins approved these changes

2023-02-27 18:45 UTC, merged