Use astro-dnssd for discovery
openmsupply/open-msupply pull request #1232
Opened 2023-02-23 04:22 UTC by mark-prins

Fixes #1064 

# 👩🏻‍💻 What does this PR do? 
 
I've been hitting the seg fault a lot lately, and wanted to get a more permanent fix in place, so I tried the astro-dnssd implementation on macOS and it worked fine. 

So, just swapped out the `async-dnssd` for `astro-dnssd` 

# 🧪 How has/should this change been tested? 

Run the server a few times, and see if it crashes 🤷 
Check that discovery is working from a macOS machine. You can try a tablet, or the desktop app or `dns-sd -Q _omsupply._tcp.local ANY` from a terminal.

## 📃 Documentation

_No user facing changes_

2023-02-28 23:45 UTC, andreievg requested changes
Nice, good to have a common lib, and from testing so far it's very solid.

I think below is better then looping. I would assume the reason the loop was needed was because `_service` is dropped, it's not returned by Ok, but an await at that point should work fine. I've tested below:
* Started electron first
* Started server
* Electron found server when it started
* Went to make tea
* After making tea started Android, seems to find it still
* Did refresh search on electron, seem to find it first.
I'll try to leave this over lunch, see if it still finds

```diff
-        // need to keep the thread running
-        // found that the discovery client in electron did not pick up the server at times
-        // and running register again was necessary for the server to be found
-        loop {
-            let service = DNSServiceBuilder::new(SERVICE_NAME, port)
-                .with_txt_record(text_record.clone())
-                .with_name(NAME)
-                .register();
-            {
-                match service {
-                    Ok(_service) => {
-                        tokio::time::sleep(std::time::Duration::from_secs(60)).await;
-                    }
-                    Err(e) => {
-                        log::error!("Error registering discovery: {:?}", e);
-                        break;
-                    }
-                }
-            }
+
+        let registration_result = DNSServiceBuilder::new(SERVICE_NAME, port)
+            .with_txt_record(text_record.clone())
+            .with_name(NAME)
+            .register();
+
+        match registration_result {
+            Ok(_service_handle) => futures::future::pending::<()>().await,
+            Err(e) => log::error!("Error registering discovery: {:?}", e),
         }
     });
```

2023-03-01 01:01 UTC, andreievg commented
After lunch, checked again with refresh, still showing up 👍

2023-03-01 02:58 UTC, mark-prins commented
Thanks @andreievg - changes are much neater. Done in 16b64b093

2023-03-01 21:09 UTC, andreievg approved these changes
Thanks Mark, works great (btw i didn't stop server, i tried yesterday at home and now, still finding it 🎉)

2023-03-01 21:33 UTC, merged