#1205 BasicTextInput and left aligned JSONForm number input
openmsupply/open-msupply pull request #1241
Opened 2023-02-26 20:23 UTC by roxy-dao

Fixes #1205 

# 👩🏻‍💻 What does this PR do? 
Have the basic text input box sx passed through props so that it doesn't mess with other components.

# 🧪 How has/should this change been tested? 
- Go an inbound shipment and see that the required field still looks the same...
- Number input components should no longer be left aligned

## 💌 Any notes for the reviewer?
This was a programs issue, but did it in develop since seemed relevant to other components too

2023-02-26 20:23 UTC, roxy-dao commented on client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx
> -      {isRequired && (
Was done before the text input refactor... forgot to remove 🤔

2023-02-26 21:24 UTC, clemens-msupply commented on client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
> +  boxSx?: SxProps<Theme>;
there is an `sx` a `boxSx` and and `InputProps.sx` now. For a basic text input this is a bit confusing to me :) At least we should document more clearly what they do. Can sx and boxSx somehow merged? @mark-prins maybe you have a better idea?

2023-02-26 21:24 UTC, clemens-msupply commented on client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
> +      alignItems: 'center',
Should we have this as default behaviour? if boxSx is not specified?

2023-02-27 02:00 UTC, mark-prins requested changes
if I can pop in a suggestion..

https://github.com/openmsupply/open-msupply/compare/feature/programs...1205-suggestion

you can achieve the same result with a single file change - which brings the `Number` JSONForm component in line with the `Text` component. 

The name of the boxSx prop is too unspecific for me - it doesn't indicate what it affects. Probably better to have an alignment prop and pass in a flex-start alignment. Not required though, afaics.

2023-02-27 02:06 UTC, mark-prins commented
Note: the offending change was something I suggested in #1103

2023-02-27 18:46 UTC, closed without merging

2023-02-27 18:52 UTC, roxy-dao commented
> if I can pop in a suggestion..
> 
> [feature/programs...1205-suggestion](https://github.com/openmsupply/open-msupply/compare/feature/programs...1205-suggestion)
> 
> you can achieve the same result with a single file change - which brings the `Number` JSONForm component in line with the `Text` component.
> 
> The name of the boxSx prop is too unspecific for me - it doesn't indicate what it affects. Probably better to have an alignment prop and pass in a flex-start alignment. Not required though, afaics.

I think we could just PR the changes you made in suggestions? XD Thanks Mark~