Assign requisition_number and invoice_number to transfers
openmsupply/open-msupply pull request #1495
Opened 2023-04-05 04:10 UTC by mark-prins

Fixes #1239

# 👩🏻‍💻 What does this PR do? 
 
When a response requisition or an inbound shipment is created automatically by the central server, if the server is unable to determine the next number in the sequence for the destination store, then it simply assigns `-1` on the expectation that the store will allocate the number when processing the transfer.

omSupply wasn't allocating - resulting in `-1` for the `invoice_number` and `requisition_number` - this is a problem as we are using the number to lookup the shipment / requisition.

This change is to watch out for `-1` and allocate a number if required.

In addition - the response requisition was not mapping status from `sg` which resulted in an error when processing. This then causes problems - because the linked requisition doesn't exist, the requisition processing is blocked.

# 🧪 How has/should this change been tested? 

Create an outbound shipment in an mSupply store, sending stock to an omSupply store. Add a line and finalise.
This will create an inbound shipment for the destination store. Check that this has a valid invoice_number.

Similarly - create an internal order in an mSupply store, requesting stock from an omSupply store.

## 💌 Any notes for the reviewer?

Have added a log entry when the number is allocated. For example, with a requisition:

<img width="907" alt="Screenshot 2023-04-05 at 4 02 13 PM" src="https://user-images.githubusercontent.com/9192912/229978752-82eec5bf-1537-49a3-8014-3579305cd5e3.png">

## 📃 Documentation

_No user facing changes_

2023-04-05 04:12 UTC, mark-prins commented on server/service/src/processors/transfer/shipment/create_inbound_shipment.rs
> +            // generate lines for the inbound shipment
the inbound shipment had no rows, so I had to add them 🤷

2023-04-05 04:12 UTC, mark-prins commented on server/service/src/sync/translations/requisition.rs
> +            LegacyRequisitionStatus::Sg => RequisitionRowStatus::New,
returning `None` meant that the fn which is mapping the status raises an error. This prevents processing of requisitions.

2023-04-06 03:00 UTC, andreievg requested changes
Thanks @mark-prins, at first I was going to suggest that we don't do this and let mSupply fix this by not creating transfer for omSupply site, but then realised this code would be needed in the future when we migrate for mSupply sites.

I still think we need to make an issue for:
* mSupply to not generate transfers for omSupply site when requesting site is active on central, i think it's this one: https://github.com/openmsupply/open-msupply/issues/1396
* When mSupply does generate supplier invoice (for mSupply site) to not duplicate item_line_id of customer invoice line in supplier invoice line (otherwise these will fail to integrate in supplier invoice site), btw this would be part of Migration work

The requested changes are (as per comment)
* Separate processors
* New creation of invoice lines would create duplicates

2023-04-11 03:33 UTC, mark-prins commented
thanks @andreievg changes made in 6f1581415
Have removed the creation of lines - so that the lines are not duplicated in mSupply and do not exist in omSupply.
Creating an issue on mSupply repo to fix that now.

2023-04-11 04:02 UTC, mark-prins commented
Issue [#1512](https://github.com/openmsupply/open-msupply/issues/1512) created

2023-04-12 13:58 UTC, andreievg commented on server/service/src/sync/translations/invoice_line.rs
> +        let is_stock_line_valid = match stock_line_id {
Hmm, i don't actually agree with this change, I'll point it out in the issue you've created for mSupply (to get this PR merged), I think not having stock line referenced by active record on site should be logged and not silently ignored (previously row would have been missing but logged against sync_buffer)

2023-04-12 14:01 UTC, andreievg approved these changes
Thanks @mark-prins, please see comment I've added: https://github.com/sussol/msupply/issues/12729#issuecomment-1505306848

2023-04-12 22:17 UTC, mark-prins commented
🙏  thanks @andreievg 
have added a warning to the log, and a TODO to take out the stock_line_id change.

2023-04-12 22:17 UTC, merged