1506 program requisitions display program data in requisition
openmsupply/open-msupply pull request #1568
Opened 2023-04-19 02:24 UTC by jmbrunskill

Fixes #1506 

# 👩🏻‍💻 What does this PR do? 
 

![image](https://user-images.githubusercontent.com/8287373/232949800-2c3e4f26-8c85-4380-b529-ec80154c58ec.png)

![image](https://user-images.githubusercontent.com/8287373/232950190-e45ec1ee-0c92-42f2-9c79-67cbbc9f7ec5.png)

# 🧪 How has/should this change been tested? 
Haven't done a lot of testing.
I created the program information manually in my database as I was waiting on #1481 

## 💌 Any notes for the reviewer?

Currently this doesn't remove the columns if programs aren't in use.
This could be addressed in a later issue.

## 📃 Documentation

- [ ] Program information visible on Requisitions (ResponseRequistions) and Internal Orders (RequestRequistitions)

2023-04-19 20:50 UTC, mark-prins commented
Can I check the intention of the program table? 
The id field has a FK to the `master_list.id` and there's also a `master_list_id` column which also has an FK on `master_list.id`. Can we remove one of these?
Also, the data that has come in from mSupply has an mSupply sourced program id and because that isn't a master_list id I can't use it. I would revert back to the mSupply usage of an `id` distinct from the `master_list.id` - would you prefer to drop the `master_list_id` column and update the translation? 

Keeping them distinct means that we can change the master list which is associated with a program. Is that valid though?

2023-04-19 21:04 UTC, mark-prins requested changes
Thanks! looking good. I have a slightly related concern about data structure, which I now think has been made on the wrong PR, soz. 
Some other requested changes in the comments

2023-04-19 21:04 UTC, mark-prins commented on client/packages/requisitions/src/ResponseRequisition/DetailView/Toolbar.tsx
> +          </Box>
The panel is squashed up - and I don't see the need. How does this look?
Also, no need for the whole box bit if the `showInfo` is false, so I lifted that up
```suggestion
          {showInfo && (
            <Box padding={2}>
              <InfoPanel message={t('info.no-shipment')} />
            </Box>
          )}
```

was:
<img width="985" alt="Screenshot 2023-04-20 at 8 59 11 AM" src="https://user-images.githubusercontent.com/9192912/233199289-c1068cc2-276f-49fc-b1dd-52883af6a7e5.png">


now:

<img width="908" alt="Screenshot 2023-04-20 at 9 02 11 AM" src="https://user-images.githubusercontent.com/9192912/233199307-45e4c1ed-b701-48b6-9906-40c772c0ad87.png">

2023-04-19 21:04 UTC, mark-prins commented on client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
> +        sortable: true,
can you remove sortable from these too please

2023-04-21 04:15 UTC, jmbrunskill commented on client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
> +        sortable: true,
Thought I'd just add sorting support instead while I'm here...

2023-04-21 05:01 UTC, mark-prins approved these changes
Looks great thanks!

2023-04-21 05:12 UTC, merged