Dashboard tweak
openmsupply/open-msupply pull request #1649
Opened 2023-05-01 04:09 UTC by mark-prins

Fixes #1647 

# 👩🏻‍💻 What does this PR do? 
 

- [ ] Change `New requisitions` to just be `Requisitions`
- [ ] Change the `Today` under `New requisitions` to be `New`
- [ ] Move `packages/invoices/src/OutboundShipment/Dashboard/Widget` to `packages/dashboard/src/widgets` and rename to `DistributionWidget`
- [ ] Move `packages/invoices/src/InboundShipment/Dashboard/Widget` to `packages/dashboard/src/widgets` and rename to `ReplenishmentWidget`
- [ ] Change the heading `Shipments that have not been shipped` to `Shipments`, AND
- [ ] Change the wording `Today` under it to `Have not been shipped
- [ ] Add `Internal orders` Stats panel with `Not sent` as a count
- [ ] Add a badge on the internal orders menu item showing the count of orders which are not sent
 

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/9192912/235405394-5a095379-0628-4f08-bed3-caecbfd07547.png">

# 🧪 How has/should this change been tested? 

Start site, check dashboard.

## 📃 Documentation

- [ ] Update screenshot of dashboard?

2023-05-01 21:26 UTC, roxy-dao requested changes
Most of the stats work great! Thanks Mark (: 

Just a few requests below 🙏🏻

2023-05-01 21:27 UTC, roxy-dao commented on client/packages/dashboard/src/api/hooks/statistics/useRequestCounts.ts
> +  return useQuery(api.keys.response(), api.get.requestRequisitionCounts, {
```suggestion
  return useQuery(api.keys.request(), api.get.requestRequisitionCounts, {
```
(:

2023-05-01 21:27 UTC, roxy-dao commented on client/packages/dashboard/src/api/hooks/utils/useDashboardApi.ts
> +    inbound: () => [...keys.count(), 'inbound'] as const,
Missing request (:

2023-05-01 21:27 UTC, roxy-dao commented on client/packages/dashboard/src/widgets/ReplenishmentWidget.tsx
> +    error: responseCountError,
```suggestion
    error: requestCountError,
```
(:

2023-05-01 21:29 UTC, roxy-dao commented on client/packages/host/src/components/Navigation/ReplenishmentNav.tsx
> +            badgeProps={getBadgeProps(requestCount?.draftCount)}
The badge looks great. Find it a bit weird to have it just for `Internal Orders` though... 
https://github.com/openmsupply/open-msupply/issues/1647#issuecomment-1529296336

2023-05-01 21:45 UTC, roxy-dao commented on server/service/src/dashboard/requisition_count.rs
> +    fn draft_request_requisition_count(
Could you refactor these so requisition_count returns both response and request counts in api? 
`invoice_counts.rs` has an example of this with outbound/inbound counts~

2023-05-02 03:17 UTC, mark-prins commented
Thanks @roxy-dao - have made the changes. I've gone with a single requisition count query, so that we only need to make the single api call from the f/e. Ideally the response would have separate permissions for each part (request / response) : since they are both using the `Resource::RequisitionStats` permission, I have that at the top level. the query returns an error if you don't have that permission, and both widgets fail to show.

2023-05-02 03:31 UTC, roxy-dao approved these changes
LGTM~ Thanks Mark (: 

Just some conflicts to deal with~

2023-05-02 04:43 UTC, merged