Fix cors for ip connection
openmsupply/open-msupply pull request #1677
Opened 2023-05-04 05:17 UTC by andreievg

OOPS this was committed to develop by accident, making a PR to show the changes, will close if ok, otherwise will make changes and re-base to develop

Fixes #1676

# 👩🏻‍💻 What does this PR do? 

Allow cors if sec-fetch-site header is missing (this happens in chrome when connecting by IP)

Fix cross-site cors 😱 , i don't know how this happened, in this PR: https://github.com/openmsupply/open-msupply/pull/802, i made a mistake and then [Clemens caught it,](https://github.com/openmsupply/open-msupply/pull/802#discussion_r1025875304) and i made a commit, but somehow it was reverted (didn't investigate, glad we caught it now thought)

# 🧪 How has/should this change been tested? 

Run release remote server or comment out is_debug statment in cors.rs. (either way make sure front end is pre-built)

Try opening localhost:8000 in browser (should work).
Try opening {your ip address}:8000 in browser (should not work without this change)

Now to validate that cross site is still forbidden, start web app with yarn start-local, and try opening {your ip address}:3003 (should work without this change and shouldn't work with this change)

`should not work` above means, login page is opened, but font styles are wrong and API requests are returned with 400

## 💌 Any notes for the reviewer?

## 📃 Documentation

2023-05-04 21:24 UTC, mark-prins requested changes
I'm trying to test - have built the server and am running the release version, connecting via desktop keeps giving me this: 

<img width="304" alt="image" src="https://user-images.githubusercontent.com/9192912/236333057-47134a90-d64e-473f-81e6-3ef3a0666cd9.png">

Not sure why yet.. just thought I'd mention.

I have a suggestion too. If you add this change https://github.com/openmsupply/open-msupply/compare/1676-allow-cors-for-same-ip-suggestion

then you can see a little more info on the info icon:

![Screenshot 2023-05-05 at 9 12 44 AM](https://user-images.githubusercontent.com/9192912/236333319-82123ee0-d334-4d28-8e1a-16d04d26d211.png)

2023-05-04 21:51 UTC, mark-prins approved these changes
> I'm trying to test

I had built a debug build, and was running a ( much older ) release build 🙄 
The web version is working fine, I still have the fingerprint issue when testing via desktop and cannot proceed past choosing a server. keeps redirecting back like this:


https://user-images.githubusercontent.com/9192912/236337787-13729c5f-7f84-4d7a-b47e-c36f96e2d071.mp4

2023-05-04 22:36 UTC, mark-prins commented
Have cleared the electron persistent store and that resolves fingerprint error. have made a note in https://github.com/openmsupply/open-msupply/issues/1685

2023-05-05 01:01 UTC, andreievg commented
> Have cleared the electron persistent store and that resolves fingerprint error. have made a note in https://github.com/openmsupply/open-msupply/issues/1685

epic 

thanks, closing, changes is already in

2023-05-05 01:01 UTC, closed without merging