Set location to state so it updates
openmsupply/open-msupply pull request #1716
Opened 2023-05-08 23:35 UTC by roxy-dao

Fixes #1702 

# 👩🏻‍💻 What does this PR do? 
Sets stock location to state, so that it changes on UI when user changes locations

# 🧪 How has/should this change been tested? 
- Have stock line with location already saved 
- Go to edit stock
- Change location and see it reflected in UI

2023-05-09 22:14 UTC, mark-prins requested changes
The state isn't required - would you mind changing please?
The problem is that the component isn't re-rendering because the `location` on draft is being used for the value, but we are updating the `locationId`
changing this, so that the `location` is updated on the draft, is all that's required to make it work

2023-05-09 22:14 UTC, mark-prins commented on client/packages/system/src/Stock/Components/StockLineForm.tsx
> +              }}
```suggestion
              onChange={location => {
                onUpdate({ location, locationId: location?.id });
              }}
```

2023-05-09 22:14 UTC, mark-prins commented on client/packages/system/src/Stock/Components/StockLineForm.tsx
> +              value={location ?? draft.location ?? null}
```suggestion
              value={location}
```

2023-05-09 22:14 UTC, mark-prins commented on client/packages/system/src/Stock/Components/StockLineForm.tsx
> +  const [location, setLocation] = useState<LocationRowFragment | null>();
```suggestion
  const location = draft.location ?? null;
```

2023-05-10 00:40 UTC, roxy-dao commented on client/packages/system/src/Stock/Components/StockLineForm.tsx
> +  const [location, setLocation] = useState<LocationRowFragment | null>();
[d7cb9a7](https://github.com/openmsupply/open-msupply/pull/1716/commits/d7cb9a7784e636ac1ef5f46c343021b8eed6ff84) 🙏🏻

2023-05-10 01:00 UTC, mark-prins approved these changes
🙏

2023-05-10 01:03 UTC, merged