Fix translations for unitssss
openmsupply/open-msupply pull request #2112
Opened 2023-08-18 04:07 UTC by roxy-dao

Fixes #

# 👩🏻‍💻 What does this PR do? 
From 
![Screenshot 2023-08-18 at 4 04 50 PM](https://github.com/openmsupply/open-msupply/assets/61820074/186dce27-bc35-4858-9295-ad28b1634672)
to
![Screenshot 2023-08-18 at 4 04 16 PM](https://github.com/openmsupply/open-msupply/assets/61820074/11777f8e-90a9-4e7b-8f8d-387d7a408c8b)
Probably only bugging out for me though 😭 

# 🧪 How has/should this change been tested? 
- [ ] Add an item that doesn't have a unit name to an invoice line and shouldn't see the extra 's'

## 💌 Any notes for the reviewer?

## 📃 Documentation

_No user facing changes_

or

- [ ] Functional change 1
- [ ] Functional change 2

2023-08-18 04:08 UTC, roxy-dao commented on client/packages/common/src/intl/locales/en/distribution.json
> -  "label.unit_one": "{{unit}}",
couldn't find this label.unit_one in the es translation file so have deleted from all

2023-08-18 07:16 UTC, mark-prins requested changes
`catalogue.json` has `label.units` and this can be removed now
`tet/distribution.json` has 
```
  "label.units_one": "{{Unidade}}",
  "label.units_other": "{{Unidade}}s",
  "label.units-in-pack-size-of_one": "{{Unidade}} iha pakote husi",
  "label.units-in-pack-size-of_other": "{{Unidade}}s iha pakote husi",
```

all of which can go too!

The OutboundLineEditForm and the PrescriptionLineEditForm are both using `'label.unit'` with a `count` prop though. The 'label.unit_one' and 'label.unit_other' were removed from distribution and not added to common.. but they will need to be. and yet most usages are wanting the translation 'Unit'.

I would suggest:
- changing `label.units-in-pack-size-of_one` to `label.in-packs-of` with a translation of `in packs of`
- removing `label.units-in-pack-size-of_other`
- adding `"label.unit-plural_one": "{{unit}}` to common.json
- adding `"label.unit-plural_other": "{{unit}}s` to common.json
- changing the two usages of `label.unit` mentioned above
- changing the usage of `label.units-in-pack-size-of` to `t('label.unit-plural', { count: xxx}) t('label.in-packs-of')`

does that make sense?
side note: I'm still unable to reproduce the original issue! using develop branch, it's fine for me 🤷

2023-08-20 21:53 UTC, roxy-dao commented
> does that make sense? side note: I'm still unable to reproduce the original issue! using develop branch, it's fine for me 🤷

So odd... been happening to me since plural was implemented 😭

2023-08-20 23:27 UTC, mark-prins requested changes
thanks Roxy - a couple more changes please; partly tidy up, and partly the plurals not working on the unit translations

2023-08-20 23:27 UTC, mark-prins commented on client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
> +                      : t('label.in-packs-of', { count: quantity })}
this block (lines 188-192) should be:

```
                      ? `${t('label.unit-plural', {
                          unit,
                          count: issueQuantity,
                        })} ${t('label.in-packs-of')}`
                      : t('label.in-packs-of')}
```

the quantity should be `issueQuantity` and `label.in-packs-of` has no params now

2023-08-20 23:27 UTC, mark-prins commented on client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
> +  console.log(item?.unitName);
can remove?

2023-08-20 23:27 UTC, mark-prins commented on client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
> +                      ? `${t('label.unit-plural', {
the `count` param here should be `issueQuantity`

2023-08-20 23:27 UTC, mark-prins commented on client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
> +                      ? `${t('label.unit-plural', {
and line 196 should be 

```
t('label.packs-of')}
```

(remove the `, { count: quantity }`) 🙏

2023-08-20 23:42 UTC, mark-prins approved these changes
🙏  thanks again Roxy!
Found a couple more bugs - this time I've just committed directly in 3e91aafd5 rather than go back and forth again.
hopefully that's the last of them!

2023-08-20 23:52 UTC, roxy-dao commented
Thanks Mark!

2023-08-20 23:53 UTC, merged