1493 remove event from activity log and add a from and to field for better translatability
openmsupply/open-msupply pull request #2330
Opened 2023-10-03 02:05 UTC by roxy-dao

Fixes #1493 

# 👩🏻‍💻 What does this PR do? 
Adds two new fields to the activity log for better translatability: `change_from` and `change_to`. Migrates the existing `event` column to `change_from` and remove it. Updated this change through backend and frontend.

# 🧪 How has/should this change been tested? 
- [ ] Go to stock line detail view
- [ ] Update any of the fields in stock line
- [ ] Go to log (currently no other translation for this other than English so....)

## 💌 Any notes for the reviewer?
Activity log translations will be broken until https://github.com/openmsupply/msupply/issues/13721 is implemented.

2023-10-03 02:07 UTC, roxy-dao commented on server/repository/src/migrations/v1_04_00/activity_log.rs
> +        ALTER TABLE activity_log ADD COLUMN change_to TEXT;
`to` and `from` are reserved, so have used alternative

2023-10-03 02:07 UTC, roxy-dao commented on server/service/src/stock_line/update.rs
> +            Some("\u{2705}".to_string()), // tick unicode
Wasn't too sure what kind of unicode to use or which way around they should be... even emojis can be country-specific! 😭

2023-10-05 20:18 UTC, roxy-dao commented on server/repository/src/migrations/v1_04_00/activity_log.rs
> +        ALTER TABLE activity_log DROP COLUMN event;
Actually... could have probably just renamed this.....

2023-10-08 21:29 UTC, roxy-dao commented on server/service/src/stock_line/update.rs
> +            None,
The log type already specifies what is happening to the stock line

2023-10-08 21:32 UTC, roxy-dao commented on server/repository/src/migrations/v1_04_00/activity_log.rs
> +        ALTER TABLE activity_log RENAME COLUMN event TO change_from;
Just renaming so all the information in previous event column will still exist

2023-10-09 01:09 UTC, mark-prins requested changes
The translation / sync needs a column rename.. otherwise, it's all good! works nicely thanks 😄 

I've put the rename into a [suggestion branch](https://github.com/openmsupply/open-msupply/compare/1493-Remove-event-from-Activity-Log-and-add-a-from-and-to-field-for-better-translatability...1493-suggestion) in case that's helpful

2023-10-09 01:13 UTC, roxy-dao commented on server/service/src/sync/translations/activity_log.rs
> +            change_to: data.change_to,
Ah right! I'm so inconsistent in writing issues 🤣

2023-10-09 03:15 UTC, mark-prins approved these changes
👍  thanks for the changes LGTM!

2023-10-09 03:37 UTC, merged