UI review Items part I
openmsupply/open-msupply pull request #978
Opened 2022-12-20 23:58 UTC by mark-prins

Fixes #856 for general items. There's a couple to address in the features branch too.

**Menu**

- [ ] highlighting of the parent menu when you are on a submenu page. It now has the parent in **bold** with the whole menu (parent+children) in a container with a box shadow. Shown as a very light grey when active, and transparent otherwise.
- [ ] when the drawer is collapsed, highlight the parent if you are on a submenu page
- [ ] add an 'external link' indication to the docs nav link

**Dashboard**
- [ ] The chart icon has been removed
- [ ] When displayed portrait on tablet, the widgets flex badly - have removed the width constraints which were mainly to accomodate the chart

**tables**
- [ ] Added an alternate row highlight in pale grey. changed the hover colour to a knocked back version of the secondary colour ( the primary looked out of place, particularly with the placeholder blue lines ). Checked with the disabled grey text and the placeholder blue text. 

### Unable to replicate 
**Site**
- The footer text is jammed together ( storename username )

### Already done
**Other components**
- Autocomplete - highlight the search terms when filtering, perhaps bold the search characters?
- Date picker - is the selected date colour the primary? it doesn't look right

2023-01-09 03:01 UTC, CarlosNZ commented
>  highlighting of the parent menu when you are on a submenu page. It now has the parent in bold with the whole menu (parent+children) in a container with a box shadow. Shown as a very light grey when active, and transparent otherwise.

![Screenshot 2023-01-09 at 4 00 04 PM](https://user-images.githubusercontent.com/5456533/211234531-5eec2183-937e-440f-900e-348c4555be4e.png)

This one's not really working for me. I think it's the way the shadows are interacting is destroying the illusion of depth. Cos the box around the parent category makes that whole block look raised, and then you have a "raised" button on top of that too. But because the button is going right to the edge of the category box, you should really the bit of shadow that spreads onto the lower background "spread" further than it is when it's only going one layer down (which is obviously not easily done in pure CSS).

I think having the parent text in Bold is enough -- do we really need two layers of shadowed items? (there's no confusion as to which parent is selected when the button of the active item is quite clear)

(Other suggestions -- maybe the parent category can just have a light "border" around it. Also, some padding between the selected button and the surround frame might help).

2023-01-09 03:04 UTC, CarlosNZ commented
> * when the drawer is collapsed, highlight the parent if you are on a submenu page

Good idea, but I think full white is too bright here -- it draws your eye too much to the side when it's not actually very relevant to the content you're looking at. When hovering, grey button on grey background looks fine (cos the drop shadow makes it stand out) -- could we just keep it the same grey when selected?

2023-01-09 03:06 UTC, CarlosNZ commented
> * add an 'external link' indication to the docs nav link

Cool, but be good to have it centered vertically (or maybe the bottom could be flush with the text base):
![Screenshot 2023-01-09 at 4 04 45 PM](https://user-images.githubusercontent.com/5456533/211234938-f9ed9426-5203-4d97-b60c-4c81d540e549.png)

2023-01-09 03:28 UTC, CarlosNZ requested changes
Cool, code all looks fine. I just have a few comments regarding the actual look of certain elements, have posted them as comments in main chat. 

Happy to discuss in person to work out best solution, or we can wait to get Anisha's thoughts?

2023-01-09 03:28 UTC, CarlosNZ commented on client/packages/common/src/ui/components/domain/Dashboard/StatsPanel.tsx
> -          </Grid>
Yeah, good call. I actually thought this was a live chart (guess I hadn't looked very hard 😄), not just a static icon -- so definitely good to remove. :)

2023-01-09 22:45 UTC, mark-prins commented
Have made changes, based on review feedback. @CarlosNZ thanks for the review & good advice!
@anisha-msupply are you able to have a look at the screenshots in here and see if they look ok?

The highlighted state when collapsed is more subtle now

![Screenshot 2023-01-10 at 9 54 24 AM](https://user-images.githubusercontent.com/9192912/211423321-d99c6568-af6e-4d50-a0d0-23d16e41c36d.png)


The submenu items have chevrons to indicate the link and are indented slightly to show their child status - without the background colour on the group.

![Screenshot 2023-01-10 at 9 53 57 AM](https://user-images.githubusercontent.com/9192912/211422834-e8db843a-ce00-4dba-8acb-f25bf59ce9a0.png)

When another menu is opened, I think that it is clear enough to see which is current, and which is open:

![Screenshot 2023-01-10 at 9 54 07 AM](https://user-images.githubusercontent.com/9192912/211422973-2f17acc0-4619-4824-991e-16b1dacfd8df.png)

The hover state is the same for children, though they aren't as high as the parent menu items:

![Screenshot 2023-01-10 at 9 54 18 AM](https://user-images.githubusercontent.com/9192912/211423096-59028c47-5b2d-4ad0-969f-7595c8c5430a.png)


**Bonus!** have moved the badge component, so that it is more closely aligned with the text:

<img width="260" alt="Screenshot 2023-01-10 at 10 06 45 AM" src="https://user-images.githubusercontent.com/9192912/211422390-40fe4a88-01f9-417c-aea9-7572b1220b6a.png">
<img width="185" alt="Screenshot 2023-01-10 at 11 24 00 AM" src="https://user-images.githubusercontent.com/9192912/211422480-85a64f13-2299-4ab4-9707-26747ad3de1c.png">
<img width="284" alt="Screenshot 2023-01-10 at 11 26 01 AM" src="https://user-images.githubusercontent.com/9192912/211422483-1dd4d1ae-5e3b-4156-a95e-dab406cabff5.png">

then went a little further. I was concerned that the vertically centred, padded external link icon was inconsistent, so have turned that into a badge, using the same styles as the standard nav link badges:

<img width="175" alt="Screenshot 2023-01-10 at 11 33 05 AM" src="https://user-images.githubusercontent.com/9192912/211422664-188621ce-ac6d-4b3f-ae73-b272519e0f60.png">
<img width="262" alt="Screenshot 2023-01-10 at 11 33 13 AM" src="https://user-images.githubusercontent.com/9192912/211422669-165c658f-d940-4f0d-a937-07f0edc10828.png">

2023-01-11 20:42 UTC, anisha-msupply commented
> @anisha-msupply are you able to have a look at the screenshots in here and see if they look ok?

Looks good @mark-prins!

I agree with @CarlosNZ on the external link icon 

I do have a couple of suggestions re menu item states - the selected child item should look most prominent, followed by the parent item and then the hover state. I'm going to mock up what this could look like, or happy to discuss in person :)

2023-01-11 20:55 UTC, mark-prins commented
Thanks for reviews 🙏 
Have reverted the external link icon changes in bc6c3276b and will create a new issue for the further menu changes

2023-01-11 20:55 UTC, merged